version: '3.8'

services:
  icecast:
    build: icecast
    environment:
      SERVICE_FQDN_STREAM_8000:

      MPD_ICE_PASSWORD: ${MPD_ICE_PASSWORD}
      ICE_ADMIN_PASSWORD: ${MPD_ADMIN_PASSWORD}
    restart: unless-stopped
  mpd:
    build: mpd
    environment:
      # Using Coolify's magic environment variables
      - SERVICE_FQDN_STREAMCONTROL_8000
      - MPD_ADMIN_PASSWORD=${MPD_ADMIN_PASSWORD}  # Editable in Coolify's UI
      - MPD_ICE_PASSWORD=${MPD_ICE_PASSWORD}      # Editable in Coolify's UI
    volumes:
      - ./music:/audio
      - ./mpd-data:/var/mpd
    restart: unless-stopped