version: '2'

services:
  icecast:
    image: vitiman/alpine-icecast:latest
    ports:
      - "8000:8000"
    environment:
        SERVICE_FQDN_STREAM_8000:

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    image: vitiman/alpine-mpd:latest

    ports:
      - "6600:6600"
    depends_on:
      - icecast
    environment:
        SERVICE_FQDN_STREAM_6600: /mpd
    volumes:
      - ./mpd_music:/var/lib/mpd/music
      - ./mpd_playlists:/var/lib/mpd/playlists
      - ./mpd_database:/var/lib/mpd/database

  sima:
    image: vitiman/alpine-sima:latest
    depends_on:
      - mpd

  ympd:
    image: vitiman/alpine-ympd:latest
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    environment:
        SERVICE_FQDN_STREAM_8080: /ymdp